name: picacgPunch

on:
  push:
    branches: [ main ]    
    paths:
      - '**'
      - '!.gitignore'
      - '!README.md'
    
  schedule:
    - cron: '2 2 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04 # 使用旧版本环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Time
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    - name: Install libssl1.1
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl1.1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Build
      run: dotnet build -c Release
      
    - name: Run
      env:
        accounts: ${{secrets.ACCOUNTS}}
      run: dotnet run -- ${accounts}
